config/routes.rb
RailsWeb::Application.routes.draw do

  resources :posts
  resources :events

  

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base

	# 與 event 成為一對多關連
	belongs_to :event # 單數

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base

	# 這表示 name 屬性是必填欄位
	validates_presence_of :name

	# 與 location 做一對一關聯式資料
	has_one :location  # 單數

	# 與 attendees 做一對多關連
 	has_many :attendees  # 複數	

	#
	has_many :event_groupships
	has_many :groups, :through => :event_groupships

end

app/models/event_groupship.rb
class EventGroupship < ActiveRecord::Base
	belongs_to :event
	belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :event_groupships
	has_many :events, :through => :event_groupships
end

app/models/location.rb
class Location < ActiveRecord::Base

	# 與 event 做關聯式資料
	belongs_to :event  # 單數

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

# show,edit,update,destroy 都有重複性程式碼，可以抽出來到find_event。@event=Event.find(params[:id])
before_filter :find_event, :only => [ :show, :edit, :update, :destroy ]
# 需要密碼驗證的頁面
before_filter :authenticate, :only => [ :edit, :update, :destroy ]

def index
	# 安裝 kaminari 之後可以有分頁的套件
    # @events = Event.all
	@events = Event.order("id").page(params[:page]).per(3)

    # 支援XML、JSON、Atom 的輸出
	respond_to do |format|
		format.html # index.html.erb
		format.xml { render :xml => @events.to_xml }
		format.json { render :json => @events.to_json }
		format.atom { @feed_title = "My event list" } #index.atm.builder
	end
end

def new
    @event = Event.new
end

# 處理由 new 表單送過來的資料
def create
    @event = Event.new(event_params)
	# 必須欄位沒有的話，必須回傳 new 的樣板頁面重新修改。
    if @event.save
		flash[:notice] = "event was successfully created"
		redirect_to events_url
	else
		render :action => :new
	end
end

def show
	# page_title 顯示在 layouts/application.html.erb 的 <title> 中
	# @page_title = @event.name  # 本行已經移到下面

	# 加上 XML, JSON 的支援
	respond_to do |format|
		format.html { @page_title = @event.name } #show.html.erb
		format.xml #show.xml.builder
		format.json { render :json => { id: @event.id, name: @event.name }.to_json }
	end

end

def edit
end

# 處理由 edit 表單送過來的資料
def update
	# 必須欄位驗證失敗
	if @event.update_attributes(event_params)
		flash[:notice] = "event was successfully updated"
		redirect_to event_url(@event)
	else
		render :action => :edit
	end
end

def destroy
	@event.destroy
	flash[:alert] = "event was successfully deleted"
	redirect_to :action => :index
end


protected  

def find_event
	# 這一行 show, edit, update, destroy 都有，所以可以拿出來。
	@event = Event.find(params[:id])
end

def authenticate
	authenticate_or_request_with_http_basic do |username, password|
		username == "foo" && password == "bar"
	end
end

private

# rails 4.0 之後才有的安全設定，要宣告允許使用的變數
def event_params
	params.require(:event).permit(:name,:description)
end 



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:id, :name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/events/_form.html.erb
<%# 如果有，顯示錯誤訊息 %>
<% if @event.errors.any? %>
	<ul>
	<% @event.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>
	

<%= f.label :name, "Name" %>
<%= f.text_field :name %>

<%= f.label :description, "Description" %>
<%= f.text_area :description %>

app/views/events/edit.html.erb
<%= form_for @event do |f| %>

 	<%# new,edit 重複性程式碼改放到 _form.html.erb %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<ul>

<% @events.each do |event| %>
  <li>
  <%= link_to event.name, event_path(event) %>

  <%= link_to " (XML)", event_path(event, :format => :xml) %>
  <%= link_to " (JSON)", event_path(event, :format => :json) %>

  <%= link_to 'edit', edit_event_path(event) %>
  <%= button_to 'delete', event_path(event), :method => :delete %>
  </li>
<% end %>
</ul>
<p><%= paginate @events %></p>
<%= link_to 'New event', new_event_path %>
<%= link_to "Atom feed", events_path(:format => :atom) %>

app/views/events/new.html.erb
<%= form_for @event do |f| %>

	<%# new,edit 重複性程式碼改放到 _form.html.erb %>
	<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%# simple_format 是一種將\n換成br的 view helper %>
<%= simple_format(@event.description) %>

<%# 除錯專用 %>
<%= debug(@event) %>

<p><%= link_to 'Back to index', events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Event application" %> </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%# 顯示錯誤訊息 %>
<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.name %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @post.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>